### ISSUE TITLE
asset deploy --build did not build the asset correctly

### ISSUE THREAD

**Issue by ciorg** [terascope/teraslice#1017]
Deployed kafka_asset v 2.0.3 to cluster when I tried to update the job to use kafka:2.0.3 I got this error
```
Failure to update job, caused by  
Error: Failure validating job: Error: Failure loading reader: kafka_reader, error:  
Error: Cannot find module   '/app/assets/5c8cdf5f4a2d20e1b352a38ed9c542fcc69e9b0a/src/kafka_reader'
```
Once I built and deployed the asset by hand it worked fine.
I think this is because this asset uses a build script that the --build command was not picking up on.

**Comment by godber** [comment]
I thought this was resolved here:

https://github.com/terascope/teraslice/pull/899

but maybe I missed the mark as suggested by my comment here: https://github.com/terascope/teraslice/issues/897#issuecomment-440486481

As it turns out none of the assets have an `asset:build` but they do all appear to have `build` targets, so this interface appears to have changed.

* https://github.com/terascope/kafka-assets/blob/master/package.json#L12
* https://github.com/terascope/file-assets/blob/master/package.json#L9
* https://github.com/terascope/elasticsearch-assets/blob/master/package.json#L7 
* https://github.com/terascope/hdfs-assets/blob/master/package.json#L10
* https://github.com/terascope/alerting-assets/blob/master/package.json#L10

We'll make sure that these four build.  Then we should remove the custom asset build scripts that are currently building assets so they can't diverge.

**Comment by peterdemartini** [comment]
I am working on syncing up the asset bundles now

**Comment by peterdemartini** [comment]
This should be fixed now, assuming you are using master of the asset of bundles
