### ISSUE TITLE
teraslice-cli asset deploy fails

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2884]
When trying to deploy a bundled or unbundled asset I ran into an error with teraslice-cli deploy

```
bin/teraslice-cli.js assets deploy teraslice --bundle terascope/file-assets
Unable to download terascope/file-assets asset: Error: Error downloading terascope/file-assets: Error: Could not find a release for terascope/file-assets (darwin x64)
    at GithubAsset.download (/Users/godber/Workspace/terascope/opensource/teraslice/packages/teraslice-cli/dist/src/helpers/github-asset.js:58:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.handler (/Users/godber/Workspace/terascope/opensource/teraslice/packages/teraslice-cli/dist/src/cmds/assets/deploy.js:98:29)
```

**Comment by peterdemartini** [comment]
The current release of `file-assets` is [v1.4.1](https://github.com/terascope/file-assets/releases/tag/v1.4.1) which is too old to have a bundle release and since the [prerelease options are filtered out](https://github.com/terascope/teraslice/blob/master/packages/teraslice-cli/src/helpers/github-asset.ts#L51) it can't find the asset to use.

We should probably go through and mark all the latest "prerelease" of our asset bundles to be the "releases" so we can use the bundled assets

**Comment by godber** [comment]
Addressed here:

https://github.com/terascope/teraslice/pull/2887

**Comment by godber** [comment]
The change here was to make the error message like this when version is not specified.

```
Unable to download terascope/file-assets, you can download a prerelease asset by specifying its version.

Example:
	terascope/file-assets@v1.2.3
```
