### ISSUE TITLE
dockerRun should exit with an error if docker run fails

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3277]
This appears to be trying to do some error handling:

https://github.com/terascope/teraslice/blob/18f617606b8c8287aac536893b52048bc40bff89/packages/scripts/src/helpers/scripts.ts#L295-L315

but when the port is in use all of the downstream scripts end up timing out after two minutes rather than failing right away when docker run returns an error.

Same story for `docker pull` with these scripts, if you try and pull a bogus image, it times out rather than erroring right away.

**Comment by ciorg** [comment]
Since I am changing some things in the ts scripts for running opensearch images I thought I would get this fixed as well.


because the function on line 301 is async the process always gets to the timeout, the async needs to throw immediately if it's a fatal error.  

Also, I'm testing with a bad opensearch version (1.0.0) and the errors I'm seeing don't have a `stack` or `all` property so they would never be seed anyway.
