### ISSUE TITLE
add ts-script bump feature for assets

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#3388]
- the scripts bump feature should be able to work with asset packages, to often we have to micro-manage the bumping the top level package.json version, the `/asset` folder package.json and asset.json version
- the script should also be able to bump the folders in the `/packages` folder and make sure the it is properly updated across the asset (both the /asset and root if its there)

**Comment by busma13** [comment]
The structure of the current bump command requires one or more packages be specified.  It seems like it would be more straight forward to create a new command (`yarn bump-asset`) to bump the package.json and asset.json in the `/asset` folder. 

When used on an asset repository  `yarn bump` would update the folders inside the `/packages` folder, just like it does in the teraslice repo. 

Would that work for you @jsnoble ?

**Comment by jsnoble** [comment]
We had a discussion via zoom about the pitfalls and things to look for. We are currently looking to use a single bump command to handle it all and to be smart enough to know when its working in an asset.  There is still discussion around the exact mechanism for it to be asset aware, but the main bulk of what it needs to do is still there.

**Comment by godber** [comment]
I am pretty sure there's code elsewhere that assumes `asset/asset.json` implies a repo is an asset, so that's a safe assumption to make here as well.  But it might be easiest in the scripts to add a `{ terascope: { asset: true } }`.  It's technically copied state, but it's not likely to ever fall out of sync.  So I've suggested that when the scripts initially populate the `{ terascope: {} }` object, it should check to see if the package is an asset, and set the `asset: true` value.

It's important to keep in mind there are two use cases for bump here:

1. updating code under `packages/*`
2. updating code under `assets/*`

For  use case `1`, I think it's a great idea to have it manage the asset version automatically.  For use case `2`, I think they can try adapting:

```
ts-scripts bump pkgname
```

to 

```
ts-scripts bump  --asset
```

but if that ends up getting ugly (they have to convert a required array to an optional array when `--asset` is provided) it might make sense to consider an alternative.

**Comment by godber** [comment]
After running and walking through the `ts-scripts bump` code on a number of things on Friday it's clear that the whole intent of the tool is to bump a package version AND EVERY PLACE IT IS USED AS A DEPENDENCY.  So this is in conflict with @kstaken's suggestion on Friday.  The tool is designed to couple these things together.  The scenario Kimbro described, however, is valid and could be necessary at some point.  After pondering it a bit I came up with the following plan of action:

* Add the asset version bump, for cases where a dependency package version is bumped
* Add a manual way to bump just the asset version when no package version is bumped
* Add a `--skip-asset` flag that allows package versions to be bumped without touching the asset
* Later, add a `--skip pkgB,pkgD` flag that allows `pkgA` to be bumped without bumping `pkgB` or `pkgD`.

**Comment by sotojn** [comment]
> After running and walking through the `ts-scripts bump` code on a number of things on Friday it's clear that the whole intent of the tool is to bump a package version AND EVERY PLACE IT IS USED AS A DEPENDENCY. So this is in conflict with @kstaken's suggestion on Friday. The tool is designed to couple these things together. The scenario Kimbro described, however, is valid and could be necessary at some point. After pondering it a bit I came up with the following plan of action:
> 
> * Add the asset version bump, for cases where a dependency package version is bumped
> * Add a manual way to bump just the asset version when no package version is bumped
> * Add a `--skip-asset` flag that allows package versions to be bumped without touching the asset
> * Later, add a `--skip pkgB,pkgD` flag that allows `pkgA` to be bumped without bumping `pkgB` or `pkgD`.

To add to the first bullet point,

When a dependency package version is bumped, the asset version will bump based on how the dependency was bumped. For example if the dependency package was bumped by a patch, then the asset version will also be bumped by a patch.

**Comment by busma13** [comment]
Using the existing bump command on an asset fails with an error and modifies the following files:
- ./package.json
- ./tsconfig.json
- asset/package.json
- packages/*/package.json
- It also creates multiple README.md and overview.md files

Most of the changes are additions, but tsconfig.json has 2 properties that are overwritten (`"include": ["test"]` -> `"include": []`) or deleted (`"outDir": "dist"`).

My next step is to check if we can easily merge instead of overwrite.

**Comment by godber** [comment]
This is sufficiently complete future work filed in related issue.
