### ISSUE TITLE
Add force option to teraslice-cli jobs and tjm stop commands

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/teraslice#3501]
Add a force option to teraslice-cli to the `jobs` and `tjm` stop commands.
### Documentation
https://terascope.github.io/teraslice/docs/management-apis/endpoints-json#post-v1jobsjobid_stop

### Commands
- `teraslice-cli jobs stop`
- `teraslice-cli tjm stop`
### Options
- `-f` and  `--force`
### Example using curl
```bash
curl -sS -XPOST 'localhost:80/v1/jobs/<jobid>/_stop?force=true' | jq 
{
  "status": "terminated"
}
```

**Comment by godber** [comment]
We've decided against implementing this, we will add a separate command in the future to accommodate it, not only that, we intend to re-implement this functionality as a separate Teraslice HTTP API endpoint as described here https://github.com/terascope/teraslice/issues/3519.  So instead of `/JOBID/_stop?force` it will be a completely different action on a job.
