### ISSUE TITLE
Modify k8s-env script to launch teraslice into any kubernetes cluster

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3586]
Currently the `k8s-env` script starts a kind cluster and then launches teraslice into it. It would be nice to be able to pass a flag called `--cluster` or `--context` that would let us launch teraslice into an already running k8s cluster.

**Comment by godber** [comment]
Let's use `--kube-context` like helm does.

**Comment by busma13** [comment]
Thoughts on passing in a file (yaml or json) that would include all the relevant info we need?
- context
- namespace
- k8s environment (k8s, minikube, kind)
- teraslice-image

**Comment by godber** [comment]
Yeah this issue is a little to wishy washy, let's punt on implementing this now.

The fundamental problem is that once you stop assuming `kind` then the question of how to get images into Kubernetes becomes a problem.  Then you have to ask questions about what use case are we really serving?  If its the dev use case, we are using cached or just built images that need pushing into the environment.  Its easier in a non-dev use case, where the user will use an existing image that can be pulled from the internet.  We don't really want to rebuild the non-dev use case since there are other tools for that and anything we do choose to do related to that should be driven around the helm chart.

So, it's too messy and doesn't have immediate benefit.
