### ISSUE TITLE
ci tests

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#3719]
The `verify build` is a simple linting test and has no bearing on the code functionality itself. If that fails, which could happen for many reasons, the tests should not be skipped.

**Comment by godber** [comment]
This is not quite true, as Joseph pointed out in the meeting today, we moved `verify build` out in front because it runs `yarn setup` which absolutely IS a prerequisite to all tests working.  So rather than changing the job so it doesn't run first ... (https://github.com/terascope/teraslice/blob/master/.github/workflows/test.yml#L30-L52)

Make it so that even if `yarn lint` fails, the job still passes.  Maybe something like `yarn lint || true` or maybe `yarn lint` can be run or configured to not return an non-zero exit code.

**Comment by jsnoble** [comment]
This might be a misunderstanding of the code or the flow of tests as they currently are, but each test individually checkouts the code, builds fresh, then runs the tests. There is no uniqueness from the `verify-build` from every other test other than the final two commands which are `yarn lint` and `yarn sync --verify` which both are non-necessary for any test to run. 

Every test checks out the code, the node version and runs yarn setup. They do not rely on something prebuilt, nothing is shared.

To my limited knowledge no environment is shared unless there is an artifact made and stored temporarily for others to reference but we don't do that. So there is no reference for this to anything else

**Comment by godber** [comment]
Jared and I talked and we decide to move the `lint` and `sync` steps out into their own job which can fail without disrupting other tests.
