### ISSUE TITLE
Fix ts-scripts (docker) images test, also rename to be more explicit

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3728]
This test was disabled as part of the ESM refactor:

https://github.com/terascope/teraslice/blob/master/packages/scripts/test/images-spec.ts#L36

It should be re-enabled or re-implemented in a way that is compatible with ESM.

Also, anywhere the test says just "images" ... reconsider the wording to be more explicit, we're talking about "docker images" here right?  A quick read without context is a little hard to understand.

**Comment by busma13** [comment]
I'm leaning toward removing this test. I don't see any good way to refactor this code. In the end some functions will need to be mocked or spied because we can't call `docker pull` or `docker save`. 

Two options I don't like:
- Create a `dryrun` flag that will skip any docker command and then return a value from the functions that call docker commands so that the test has some change to test against. Passing a return value that is only used for testing seems wrong though.
- Create a `dryrun` flag that skips docker commands, but saves a fake file to the cache. That way we know `saveAndZip` was called at least.

**Comment by godber** [comment]
It's probably safe to delete this skipped text.
