### ISSUE TITLE
Teraslice serial job startup with cluster_manager_type set to kubernetesV2

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3868]
Description from internal ticket:

## Background

Jobs now appear to startup serially when setting cluster_manager_type to kubernetesV2

A typical action to perform in production is to stop/start batches of related jobs.  Thirty jobs might take about 5 minutes with kubernetes, but with kubernetesV2 this now takes over 30 minutes.

The version of teraslice does not have a bearing on the job start up behavior.

Issue could be that at job startup there is no concurrency and all the promises have to return before moving on to the next job.

## kubernetes

Jobs appear to start up in parallel when starting more the one job at a time.  The jobs will go from pending, scheduling, initializing, and running almost at the same time.

## kubernetesV2

Jobs appear to start up serially. The jobs will all be in pending after issuing start command. Then one job will go from scheduling, initializing, and finally running.  After the job is running the next job will go to scheduling.

**Comment by busma13** [comment]
After looking into this, we were waiting for the `executionController` readiness probe to be `ready` before we created each worker deployment. Removing this bit of code seems to have solved the issue.

**Comment by godber** [comment]
> we were waiting for the executionController readiness probe to be ready before we created each worker deployment.

This isn't required, it's OK for the workers to come up and wait a bit for the execution controller to be available.  They are patient ... and should stay patient.

We used to have to wait for the execution controller pod to get an IP prior to creating the worker deployment, but that's no longer necessary and the service name is now known in advance.

Its possible jobs start even faster now since they aren't waiting on the exc pod IP anymore either.
