### ISSUE TITLE
Message/record level error handling? - dead letter channel

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#450]
Looks like error handling is done only at the slice level.  I'm looking for some sort of [error channel or dead letter channel](http://www.enterpriseintegrationpatterns.com/patterns/messaging/DeadLetterChannel.html) to write exceptional msgs/records to.  I don't want the entire slice to fail due to a small fraction of failures.  Use cases I'm thinking of:

1. Garbage in.  Retrying the slice won't help.  Gracefully redirecting the garbage somewhere will better allow clients gauge how impactful it is and what to do about it.

1. Transient external exceptions (eg network, disk, or external service outage).  I wouldn't want to hold up or retry an entire slice if only a small fraction of items failed to process successfully.  Sending them to another channel for retry later would be ideal for large slices.

1. Job bugs - similar to the use case above.  Retrying the slice when there is an app/job level bug will be useless.  Better to capture the unhandled cases somewhere until the job is patched to handle them.

**Comment by jsnoble** [comment]
1) The best way might be to have a schema outside teraslice for the data, so malformed data never hits the pipeline in the first place. We need to set up a contract of what it looks like especially since we need mappings for them to do any sort of queries on it. If not then your reader/slicer would have to check it yourself and determine what to return.
2) If you check out how we have our elasticsearch sender code, and the elasticsearch api code. We have to handle that ourselves. The sender bulk send at times sends up partial bulk, we have to check what wasnt sent and use exponential backoff to send up the rest
3) If this happens everything fails, or the failures shows up in the logs.

What this really means is that the common core readers/processors  that we provide have to be tested and battle hardened. The docs need to explain various circumstances an op needs to account for but its up to the people making their own custom op to make it bullet proof. This is at least of things stands now. Im not fully sure what we could do to help ease others code choices. We have the capabilities for them to implement a recover abilitiy to try to redo any failed slices but they have to make it so their slicer can handle that as well.

**Comment by kstaken** [comment]
We should definitely incorporate an API for this as part of the improved processor APIs and streaming.

**Comment by kstaken** [comment]
This will be implemented in an asset bundle but I'm going to hold this ticket open until we know where it will live.
