### ISSUE TITLE
Restore jobs as point of interaction for users

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#457]
For discussion.

@erik-stephens made the observation that the current jobs vs. ex distinction is fuzzy and confusing and I think this is the key to solving some of the operational management issues with persistent jobs.

This requires a few minor changes to our assumptions.
1. There can be many executions of the same job but ONLY one can be running at any given time.
2. All job control goes through the `job_id` rather than the `ex_id`. Execution contexts don't go away, they're still how a job is instantiated but users shouldn't be required to manipulate them directly (we may still want to keep the APIs they just wouldn't be the normal way to do things).
3. It becomes normal practice to in place update an existing job spec.

The biggest impact of this should be at the API and documentation level, I don't think it would bring huge internal changes to job execution beyond scheduling and control.

With this when you wanted to define a persistent task say `import X data` you would:
  * register the job with the system and get a job_id that's associated with the task.
  * Use that `job_id` to monitor and track the job from external systems.
  * If there is an issue with the job and it needs to be restarted then an admin can restart the job without having to have access to the job config.
  * If the job config changes then an update to the existing `job_id` would be posted and the job can be restarted. (This could also eventually be an automatic operation)
  * If the job depends on assets then the job can be restarted when new assets are published. (eventually we may have automatic facilities for this)
  * Each new execution of the job still gets a new `ex_id` and this creates a history for executions of that job.
 
This also has a few other benefits:
  * Cuts down on clutter in the jobs index
  * Opens the door for more advanced job control and supervision within teraslice it self.

**Comment by jsnoble** [comment]
Im not fully clear on why there needs to be just job_id. From the standpoint of a persistent job, it is either running/failing or will be listed (soon) as terminated which would make it easy for rescheduling. The ex_id has all the configurations that the job config would with the addition of metadata. We would probably need to add another field to the job anyways to mark it for auto restart, thus the ex will have that data. As for the holding onto the id itself, we would have to collect them anyways so having one or two id's isn't that big of a deal.  The ex_id is always unique which is good since each invocation should be unique, however its possible to submit the same job twice and get two different job_id's for them.

Im just not clear what operational benefits we will get for this change

An argument for just exposing one id is simplicity and we are not currently treating the job itself properly. We are more prone to just resubmit instead.

If we decided to go through with this, it will not be a hard of a change than I thought. It would require an additional database query to find the active ex for any job for most things.

API Change Proposal:
/ex  => leave as is  //maybe hide ex_id and just expose the job_id's
/ex/:ex_id   =>  jobs/execution/:job_id
/ex/:ex_id/_stop  =>  jobs/execution/:job_id/_stop
/ex/:ex_id/_pause  =>  jobs/execution/:job_id/_pause
/ex/:ex_id/_resume  =>  jobs/execution/:job_id/_resume
/ex/:ex_id/_recover  =>  jobs/execution/:job_id/_recover
/ex/:ex_id/_workers   =>  jobs/execution/:job_id/_workers
/ex/:ex_id/slicer   =>  jobs/execution/:job_id/slicer
/ex/:ex_id/stats   =>  jobs/execution/:job_id/stats  //this should work even if the job is done already

maybe alternative  jobs/ex/:job_id variation instead of  jobs/execution/:job_id ?

**Comment by godber** [comment]
@kstaken I am concerned with the consequences of these two things:

* "It becomes normal practice to in place update an existing job spec."
* "If the job config changes then an update to the existing job_id would be posted and the job can be restarted."

Does the job spec get copied to the `ex_id` context so there is some record of what has executed?

**Comment by jsnoble** [comment]
@godber Any time a new job is executed, all configurations are copied over. Therefore they will be identical in job configurations. However, updating a job does not change its job_id, just the job config. Thus if a job is started after the update, the ex will have the new config since its based off the new job

**Comment by godber** [comment]
@jsnoble what necessitates the extra `/execution`?  Couldn't the API operate directly on `/jobs/:job_id`?

```
/ex => leave as is 
/ex/:ex_id/_stop => jobs/:job_id/_stop
/ex/:ex_id/_pause => jobs/:job_id/_pause
/ex/:ex_id/_resume => jobs/:job_id/_resume
/ex/:ex_id/_recover => jobs/:job_id/_recover
/ex/:ex_id/_workers => jobs/:job_id/_workers
/ex/:ex_id/slicer => jobs/:job_id/slicer
/ex/:ex_id/stats => jobs/:job_id/stats
```

Any operation on a given `job_id` is implied to be on the current/active `ex_id`.

This may not be needed:

```
/ex/:ex_id => jobs/execution/:job_id
```

**Comment by kstaken** [comment]
@jsnoble this change is about production operations not anything internal to teraslice. The problem is that the ex_id changes for each job execution. That's not manageable in a production environment. The goal here is to submit a job once, get the job_id and than be able to track that one thing through the production life of the job no matter how many executions have occurred. This tracking is "external" to teraslice.

As @godber pointed out there's no reason for the "execution" level in the URL.
