### ISSUE TITLE
job state transition and tracking discussion

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#473]
This thread is meant to start a conversation regarding how job status should be handled. As it stands it fairly easy to take a job thats marked as failing, and then send a pause or stop on it and the status of failing will be clobbered. This could potentially cause a few issues.

- Its easy to lose context of whats going on internally with clobbering, especially now that we are trying to do more tracking. A job could be marked as running => failing => paused  => running and only once jobs will end up marking the job as failed, a persistent job would lose this info since it never stops, this will lead us to verify if a job is failing some other way and could be a mismatch to the job status.
- We need to think carefully how we want jobs to be restarted on startup, what should be enqueued back in line etc.
- In the pr #470 all jobs currently running when a shutdown occurs will be marked as terminated, clobbering any previous _status values.

**Comment by erik-stephens** [comment]
I don't have any specifics to add to the conversation but some general comments that might help.

Jobs will have different sensitivity to failure, so allowing the user to control that will a) be more useful and b) ease the burden of us trying to find a single best way.  We can look to other [supervisors](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) if not clear which controls we should expose to users.

Also, now would be a good time to start documenting state transitions.  I've used [js-sequence-diagrams](https://bramp.github.io/js-sequence-diagrams/) before.  I like cuz we can write them in plain text (can track changes) yet still get pretty output.  This particular tool doesn't look good for doing the complete state transition diagram but maybe that's ok since those can get messy quick.  Instead, we could use to document specific scenarios: successful once-only, successful persistent, transient failures, failed restart=never, failed restart=on-failed, pause-resume, stop-start, etc.

Regarding clobbering previous _status values, can't the complete state history for a job be constructed from its executions' state records?

**Comment by peterdemartini** [comment]
This issue should be solved in the latest version of teraslice, by making the execution status update protect against going from terminal -> running, or running -> initializing.
