### ISSUE TITLE
OP APIs for teraslice functionality and asset defined extensions

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#542]
We need to rethink how we're exposing APIs to ops.

Currently we expose `context.foundation.[functions]` and `context.assets.[functions]`. This is a "weak" form of dependency injection which has many advantages but the current mechanism feels a little adhoc.

The ops that we distribute with the code also use functions from util that they include directly: `getClient` and `getOpConfig`. As I've been writing ops I've had to copy some form of `getClient` several times which says these should also be APIs exposed to processors. 

In addition I think asset bundles are going to want to expose APIs that can be used by processors that are not part of the bundle.

So overall we need a more clear approach to how we consistently expose this type of functionality.

=============================
To start the first principle is that we want to adopt a policy that nothing puts anything into the `context` without going through an API defined by terafoundation. 

NOTE: We'll keep, but deprecate the current APIs until we're sure everything is updated.
=============================

So for this purpose, Terafoundation will define a function `context.apis.registerAPI(name, api)` that can be used by any module to register an API with the system. 

This function will then expose the API directly on the context under context.apis. All modules that want to define APIs should call this function regardless of whether they're in terafoundation, teraslice or an asset bundle.

```
context    
    apis
         registerAPI(name, api)

context.apis.registerAPI('mymodule', {
    myFunction1,
    myFunction2
});
```

Then as modules register it will expose the APIs under `context.apis` using the name. Names will have to be unique but that's a typical namespace management issue and registering over an existing name is an error.

```
context
     apis
         registerAPI(name, api)
         foundation
                makeLogger()
                ...
                getConnection()
         assets
                getPath()        
         mymodule
                myFunction1()
                myFunction2()
```

So to access the API for a module.

```
const mymodule = context.apis.mymodule;
mymodule.myFunction1();
```

**Comment by kstaken** [comment]
Bumping this to priority:high and I'll be working on this in terafoundation and teraslice. Not having this is blocking several things I'm trying to deal with.

**Comment by kstaken** [comment]
This has been completed and merged at the terafoundation level. Remaining tasks:

* switch the usage of APIs in teraslice to use the updated paths
* Make sure any APIs that are defined within Teraslice it self are using the registerAPI function. This may just be `assets`.
* Switch all readers/processors to use the API version of getClient and getOpConfig

**Comment by jsnoble** [comment]
Looking at the code base we still heavily rely on the getClient function that exists in utils/config.js instead of the context.apis.op_runner.getClient. After review I am not sure that this lives in the right spot. This api is only available after the execution class is constructed for a worker or a execution_controller. It is not available for cluster_master which has many services which need to use getClient (pretty much all of them). Also, the stores that the worker and execution_controller loads call getClient as well, but this all happens before the api is registered. Thus in the end only a few processors/reader/slicers could potentially use this api. I think we need to put this at a lower level so that it can be used across the board. However, in the end getClient is just a nice helper function of the context.apis.foundation.getConnection thats made in terafoundation. Its not really needed, it just makes it a bit easier to use and you have to specify less of the config needed for that api.

**Comment by kstaken** [comment]
I think we have a good handle on this now with `job-components`. Closing this as further changes should come in new tickets.
