### ISSUE TITLE
Slice queue stays at maximum when worker count is decreased

### ISSUE THREAD

**Issue by macgyver603** [terascope/teraslice#726]
When decreasing the worker count on a job dynamically with `_workers?remove=`, the number of queued slices did not decrease to match the new worker count.

**Comment by kstaken** [comment]
This is on a job using the kafka_reader. It's not necessarily a problem and you wouldn't expect it to reduce immediately after workers are removed but since we're setting the queue size based on the number of workers it would make sense for it to resize and then work the queue down to the expected size.

**Comment by jsnoble** [comment]
this has been addressed in the code. Having the slicer with a method of slicerQueueLength that returns the value 'QUEUE_MINIMUM_SIZE' will change the queue for as many workers are connected to it. This will not change the amount of slices that are already in the queue.
