### ISSUE TITLE
`active` attribute on jobs

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#856]
We should add a `monitor` boolean attribute to jobs. The primary usage of this would be to indicate to external monitoring systems what jobs should be monitored but it would also be useful for certain internal uses too.

In particular there should be a way to hit an API endpoint and get a list of all jobs listed as `monitor`able and their actual status on the cluster. 

Details of this will need a little thought but the driving use case for this is our inability to currently see what's 'supposed' to be running. As we've added more and more jobs, temporary and test jobs, jobs moving between clusters and jobs being replaced with new versions we need a better way to indicate a job is `important` to watch.

**Comment by godber** [comment]
Our discussion last night about how `tjm` stores cluster metadata on the job json files and how that feels like data duplication to me made me think of this ticket.  Though I hadn't remembered that you specifically chose the attribute name to be `monitor`.  I remembered it as `active`.

Rather than storing anything in the json file, assuming `monitor` is properly managed, `tjm` could just query all clusters, find which cluster has the job with the `monitor` property set.  Then perform it's action on that job on that cluster.  This would mean there is no state duplication that can become out of sync. `tjm` would be using the source of truth, the cluster state of all of the teraslice clusters.

Maybe it's not necessarily a given the cluster states of all of the teraslice clusters is the source of truth.  Perhaps that's what's up for debate.  But the distributed teraslice cluster states is definitely A source of truth.  It's definitely what's happening now.

**Comment by godber** [comment]
Then there's the question as to whether the `monitor` property as described by Kimbro in this ticket and `active` property as I've mentioned in the comment above are the same thing.  This made me wonder if instead of properties, we should provide a `tags` property that allows us to define multiple things along this line: `tag: [monitor, active]` ... teraslice could reserve certain tags for its use but allow for other tags (maybe/probably on another property) to be defined by users.  Maybe too messy.

**Comment by godber** [comment]
I think if we were to have one boolean property it would be `inactive`.  I think this matches the existing workflow the best.  You create a job, it gets registered, used for a while, then some day, that pipeline is replaced and that job is no longer used.  It's inactive, if we could delete jobs we might delete that one since we know it won't get used again.  @ciorg might even mimic this behavior in the git repo he stores jobs in ... it looks like he has a `legacy/` subdirectory that he moves disused jobs to.

Above I mentioned tags ... we now have labels:

https://github.com/terascope/teraslice/issues/1546#issuecomment-566587947

**Comment by godber** [comment]
If we were to add `inactive` it would be optional and default to `false`.

## Starting And Stopping

Users should be able to start and stop inactive jobs.  Maybe in those cases, the response should contain some sort of warning in addition to the typical response.

### start

```
curl -Ss http://ts-ops2.tera1.lan/jobs -XPOST -d@j.json
{
    "job_id": "4b3798c1-5080-4962-a3c4-29d0374f2252",
    "ex_id": "d1fe4373-7c3a-45e4-9cae-24900a9fe279",
    "message": "Warning, this job is marked inactive."
}
```

### stop

```
curl -Ss http://ts-ops2.tera1.lan/jobs/4b3798c1-5080-4962-a3c4-29d0374f2252/_stop -XPOST
{
    "status": "stopped",
    "message": "Warning, this job is marked inactive."
}
```

For that matter, stop should also return the `job_id` and `ex_id` shouldn't it?

Honestly, I'd hate to just adhoc define things in this interface here, so we should probably punt on the warnings.

## `/txt` Views

The `/txt` endpoints should exclude `inactive` jobs unless an optional query parameter is provided.  I'm not yet sure what that should be ...:

* `/txt/jobs?_all`
* `/txt/jobs?inactive=true`

## JSON APIs

I suspect the JSON apis should have the same behavior of excluding `inactive` jobs unless provided a query parameter.

Comments encouraged.

**Comment by peterdemartini** [comment]
Something feels off about it calling it `inactive`, I'd prefer to use something like `state: 'active'|'inactive'`, so that we can leave room for other states.

Also, showing a warning message when stopping/starting an `inactive` job feels wrong, I feel like the job shouldn't be allowed to be started unless it is in an `active` state, and you shouldn't be able to set a job as `inactive` unless it is stopped. Unless I am misunderstanding the use of `inactive`

**Comment by peterdemartini** [comment]
I see, maybe a better word to use is `ephemeral` instead of `inactive`, since it is a job that can run but it can come and go and is not critical. Even though the term `ephemeral` isn't perfect, [Kubernetes uses that it](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) and I think it better describes it.

Instead of using `state` (which is word we use everywhere), we could use `kind` with the options: `persistent` (or `permanent` if we don't want to conflict with `lifecycle`) or `ephemeral`

**Comment by kstaken** [comment]
The attribute here should be called `active`, defaulted to `true`.  

This could become a generally useful attribute to Teraslice it self, i.e. it could eventually refuse to start jobs that are labeled as active:false. For now we just need to have the attribute included in the schema as it should be searchable.

`ephemeral` is something completely different.

**Comment by godber** [comment]
> The attribute here should be called `active`, defaulted to `true`.

Yeah!  Makes perfect sense.

**Comment by godber** [comment]
Below are my thoughts on the API.  I can proceed with no feedback if necessary, as I indicate my decision in each case.  But now's your opportunity to speak up.

### Add Teraslice `active` Property

First off, should this be `_active` or `active`?  I ask because I just
remembered that `_status` begins with `_` (though thats on ex).

I think `active` is fine.

#### Toggling `active` on a job

I think it would be convenient to have an easy way to set these, probably like
this:

```
curl -XPOST localhost:5678/jobs/:jobId/_active
curl -XPOST localhost:5678/jobs/:jobId/_inactive
```

I don't think it makes a whole lot of sense to implement this on the `/ex/`
endpoint.

This could be omitted, but I'll include it unless there's objections.

#### `/txt` endpoints

What the user should see when hitting the following `/txt` endpoints

* `/txt/jobs` - "all" jobs
* `/txt/jobs?active=true` - jobs with `active=true` or `NOT _exists_:active`
* `/txt/jobs?active=false` - jobs with `active=false`

Should we do `/txt/ex` as well or should that be out of scope?  Unless there is
some specific reason to not do it, I will filter these as well.

* `/txt/ex` - "all" executions
* `/txt/ex?active=true` - executions with `active=true`
* `/txt/ex?active=false` - executions with `active=false`


#### JSON endpoints

What the user should see when hitting the following JSON endpoints

* `/jobs` - "all" jobs
* `/jobs?active=true` - jobs with `active=true` or `NOT _exists_:active`
* `/jobs?active=false` - jobs with `active=false`

If above we decide to do `/txt/ex` we should also do `/ex` here

* `/ex` - "all" executions
* `/ex?active=true` - executions with `active=true`
* `/ex?active=false` - executions with `active=false`

#### Augmenting `GET /jobs/:jobId`

The biggest drawback of the `active` property not being materialized in the
database is that if a user `GET`s a jobId where it isn't explicitly set, they are
going to need to know that the property being absent means that it's `true`,
which violates the law of least surprise.  One way to manage this is to add the
`active = true` when the user `GET`s a job.  I think this would then imply that
we would want to add the property in the list endpoints as well.

I think I'd be inclined to try and include this augmentation.  I'd rather try it
and see if it works out OK instead of not doing so and having to explain a
"missing" property in docs and issues for the rest of time.

#### `/cluster/state` and `cluster/slicers` Endpoints

The endpoints `/cluster/state` and `cluster/slicers` might be a little more
debatable.  To me these endpoints are about what workers/processes are running.
Whether a job is active or not has no bearing.  So I don't think I'd filter
these by active like the others, though technically it could be.

#### Other Endpoints

I've looked at the other endpoints in `api.js`, I think for the most part they
do not need modification for this change.

**Comment by kstaken** [comment]
This looks good. active won't mean much on ex but it will be propagated through so I can't think of a reason to not expose the same API.

**Comment by godber** [comment]
The implementation present in https://github.com/terascope/teraslice/pull/2142 doesn't do all of the things outlined above, it just does:

* adds the property
* adds the `_active` and `_inactive` actions on the job
* filters the `/txt/jobs` and json `/jobs` endpoint when using `?active=[true|false]`

Filtering /ex is conceptually confusing because `active` is on both the job and ex ... which would the filter apply to?  I skip it due to that ambiguity and lack of an immediate use case.

Also I skip augmenting the GET output from jobs to include the active value.  Users must KNOW that the property being absent implies that it is `active=true`.

**Comment by godber** [comment]
Resolved in https://github.com/terascope/teraslice/releases/tag/v0.70.0
