### ISSUE TITLE
Building assets using teraslice-cli should handle linked files and folders

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#876]
When `teraslice-cli` builds assets, it should handle symlinked files and folders by either copying them, following them or throwing an error.

**Comment by godber** [comment]
I understand where you're coming from here ... but this implies I keep the users working `node_modules` directory ... who knows what's gone on in that directory.  Or I continue to delete the `node_modules` dir then later overlay (copy in) the symlinks ... assuming they're good too?

Here's what I do now ... https://github.com/terascope/teraslice/blob/v0.51.0/packages/teraslice-cli/lib/asset-src.js#L70-L106

Note line 87 I delete the node_modules directory after copying the source to the temp directory.

Maybe there's a better way to accomplish this.  Maybe it should be an option.

**Comment by kstaken** [comment]
Yeah, when you're doing asset development you might want to have linked dependencies that you're working on but I'm not sure that compromising the build process is what should happen to address that. I think the way build works currently is the correct way.

For the development scenario we might want to think about encouraging the linking of the asset into the local teraslice instead of a build / deploy process anyway. That makes the development process much simpler overall assuming linked dependencies work. I've done this by deploying an asset to get an ID, then removing the directory under `assets` and replacing it with a link to my development copy.

**Comment by kstaken** [comment]
This doesn't belong in the build process.
