### ISSUE TITLE
New command `await` for job status

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#954]
We should add a new command that works in both `tjm` context and general jobs context to await on a running job reaching a particular status or any of a set of statuses. Should probably have a configurable timeout that by default is `unlimited` since jobs can run for long periods.

Something like

```
earl tjm await job.json completed
earl tjm await job.json completed,stopped
earl jobs await JOB_ID completed -t 600
```

**Comment by peterdemartini** [comment]
I like it. I recommend making the statuses configured via a flag instead of a positional argumentent so it’s easier to read and allows yargs to deal with the array parsing.

**Comment by kstaken** [comment]
Yeah that makes sense

**Comment by ciorg** [comment]
command would be:
earl jobs await CLUSTER JOB_ID --status completed,stopped --timeout 10min

earl tjm JOB.JSON --status completed,stopped
  
tjm and jobs commands _should_ share code because they do many of the same things.  Would be easier for tjm to use the jobs helper class for all job-related actions, stop, start, etc... than for jobs to use tjm helper class.

Plan is to add the await function to the jobs class and tjm will import that class.

**Comment by godber** [comment]
I have confirmed this is functional:

```
earl tjm await --start example-job.json
Started example-data-generator-job on http://192.168.64.5:30678
> job: fd8af957-743a-41a6-88d0-8e0376dbef3a current status: initializing
> job: fd8af957-743a-41a6-88d0-8e0376dbef3a waiting for status completed or stopped
> job: fd8af957-743a-41a6-88d0-8e0376dbef3a reached status: completed
```

Thanks Charlie!
